(ns irresponsible.gadget-test
  (:require [clojure.test :refer [deftest is]]))

(deftest partial*)
(deftest summary)
(deftest inspect)
(deftest gadget)
(deftest wtf?)
(deftest name)
(deftest visibility)
(deftest public?)
(deftest protected?)
(deftest private?)
(deftest static?)
(deftest dynamic?)
(deftest bases)
(deftest constructors)
(deftest fields)
(deftest methods)
(deftest params)
(deftest returns)
(deftest type)
(deftest -summarise-constructors)
(deftest -summarise-method-group)
(deftest -summarise-methods)
(deftest -summarise-fields)
(deftest -summarise-bases)
